#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUtils
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="web")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccessCount(AccessCount instance);
    partial void UpdateAccessCount(AccessCount instance);
    partial void DeleteAccessCount(AccessCount instance);
    partial void InsertCCCafeMailingListMember(CCCafeMailingListMember instance);
    partial void UpdateCCCafeMailingListMember(CCCafeMailingListMember instance);
    partial void DeleteCCCafeMailingListMember(CCCafeMailingListMember instance);
    partial void InsertSingleTweet(SingleTweet instance);
    partial void UpdateSingleTweet(SingleTweet instance);
    partial void DeleteSingleTweet(SingleTweet instance);
    partial void InsertRecurringTweet(RecurringTweet instance);
    partial void UpdateRecurringTweet(RecurringTweet instance);
    partial void DeleteRecurringTweet(RecurringTweet instance);
    partial void InsertSnabusMailingListMember(SnabusMailingListMember instance);
    partial void UpdateSnabusMailingListMember(SnabusMailingListMember instance);
    partial void DeleteSnabusMailingListMember(SnabusMailingListMember instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WebUtils.Properties.Settings.Default.webConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AccessCount> AccessCounts
		{
			get
			{
				return this.GetTable<AccessCount>();
			}
		}
		
		public System.Data.Linq.Table<CCCafeMailingListMember> CCCafeMailingListMembers
		{
			get
			{
				return this.GetTable<CCCafeMailingListMember>();
			}
		}
		
		public System.Data.Linq.Table<JuliaHaywardMailingListMember> JuliaHaywardMailingListMembers
		{
			get
			{
				return this.GetTable<JuliaHaywardMailingListMember>();
			}
		}
		
		public System.Data.Linq.Table<Website> Websites
		{
			get
			{
				return this.GetTable<Website>();
			}
		}
		
		public System.Data.Linq.Table<SingleTweet> SingleTweets
		{
			get
			{
				return this.GetTable<SingleTweet>();
			}
		}
		
		public System.Data.Linq.Table<RecurringTweet> RecurringTweets
		{
			get
			{
				return this.GetTable<RecurringTweet>();
			}
		}
		
		public System.Data.Linq.Table<SnabusMailingListMember> SnabusMailingListMembers
		{
			get
			{
				return this.GetTable<SnabusMailingListMember>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccessCount")]
	public partial class AccessCount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Site;
		
		private int _nSessions;
		
		private int _SiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteChanging(string value);
    partial void OnSiteChanged();
    partial void OnnSessionsChanging(int value);
    partial void OnnSessionsChanged();
    partial void OnSiteIdChanging(int value);
    partial void OnSiteIdChanged();
    #endregion
		
		public AccessCount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this.OnSiteChanging(value);
					this.SendPropertyChanging();
					this._Site = value;
					this.SendPropertyChanged("Site");
					this.OnSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nSessions", DbType="Int NOT NULL")]
		public int nSessions
		{
			get
			{
				return this._nSessions;
			}
			set
			{
				if ((this._nSessions != value))
				{
					this.OnnSessionsChanging(value);
					this.SendPropertyChanging();
					this._nSessions = value;
					this.SendPropertyChanged("nSessions");
					this.OnnSessionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId")]
		public int SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CCCafeMailingList")]
	public partial class CCCafeMailingListMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Name;
		
		private string _Email;
		
		private string _VerifyCode;
		
		private bool _Verified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnVerifyCodeChanging(string value);
    partial void OnVerifyCodeChanged();
    partial void OnVerifiedChanging(bool value);
    partial void OnVerifiedChanged();
    #endregion
		
		public CCCafeMailingListMember()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerifyCode", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VerifyCode
		{
			get
			{
				return this._VerifyCode;
			}
			set
			{
				if ((this._VerifyCode != value))
				{
					this.OnVerifyCodeChanging(value);
					this.SendPropertyChanging();
					this._VerifyCode = value;
					this.SendPropertyChanged("VerifyCode");
					this.OnVerifyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verified", DbType="Bit NOT NULL")]
		public bool Verified
		{
			get
			{
				return this._Verified;
			}
			set
			{
				if ((this._Verified != value))
				{
					this.OnVerifiedChanging(value);
					this.SendPropertyChanging();
					this._Verified = value;
					this.SendPropertyChanged("Verified");
					this.OnVerifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JuliaHaywardMailingList")]
	public partial class JuliaHaywardMailingListMember
	{
		
		private string _Name;
		
		private string _Email;
		
		private string _VerifyCode;
		
		private bool _Verified;
		
		public JuliaHaywardMailingListMember()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerifyCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VerifyCode
		{
			get
			{
				return this._VerifyCode;
			}
			set
			{
				if ((this._VerifyCode != value))
				{
					this._VerifyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verified", DbType="Bit NOT NULL")]
		public bool Verified
		{
			get
			{
				return this._Verified;
			}
			set
			{
				if ((this._Verified != value))
				{
					this._Verified = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Website")]
	public partial class Website
	{
		
		private int _SiteId;
		
		private string _SiteName;
		
		private string _SiteUrl;
		
		private string _TwitterId;
		
		private string _TwitterOauthToken;
		
		private string _TwitterAccessToken;
		
		public Website()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this._SiteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this._SiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteUrl", DbType="NVarChar(255)")]
		public string SiteUrl
		{
			get
			{
				return this._SiteUrl;
			}
			set
			{
				if ((this._SiteUrl != value))
				{
					this._SiteUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterId", DbType="NVarChar(50)")]
		public string TwitterId
		{
			get
			{
				return this._TwitterId;
			}
			set
			{
				if ((this._TwitterId != value))
				{
					this._TwitterId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterOauthToken", DbType="NVarChar(50)")]
		public string TwitterOauthToken
		{
			get
			{
				return this._TwitterOauthToken;
			}
			set
			{
				if ((this._TwitterOauthToken != value))
				{
					this._TwitterOauthToken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterAccessToken", DbType="NVarChar(50)")]
		public string TwitterAccessToken
		{
			get
			{
				return this._TwitterAccessToken;
			}
			set
			{
				if ((this._TwitterAccessToken != value))
				{
					this._TwitterAccessToken = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SingleTweet")]
	public partial class SingleTweet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SingleTweetId;
		
		private int _SiteId;
		
		private string _Status;
		
		private System.DateTime _TimeToTweet;
		
		private string _RetweetingSiteIds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSingleTweetIdChanging(int value);
    partial void OnSingleTweetIdChanged();
    partial void OnSiteIdChanging(int value);
    partial void OnSiteIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTimeToTweetChanging(System.DateTime value);
    partial void OnTimeToTweetChanged();
    partial void OnRetweetingSiteIdsChanging(string value);
    partial void OnRetweetingSiteIdsChanged();
    #endregion
		
		public SingleTweet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleTweetId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SingleTweetId
		{
			get
			{
				return this._SingleTweetId;
			}
			set
			{
				if ((this._SingleTweetId != value))
				{
					this.OnSingleTweetIdChanging(value);
					this.SendPropertyChanging();
					this._SingleTweetId = value;
					this.SendPropertyChanged("SingleTweetId");
					this.OnSingleTweetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="Int NOT NULL")]
		public int SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(140) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeToTweet", DbType="DateTime NOT NULL")]
		public System.DateTime TimeToTweet
		{
			get
			{
				return this._TimeToTweet;
			}
			set
			{
				if ((this._TimeToTweet != value))
				{
					this.OnTimeToTweetChanging(value);
					this.SendPropertyChanging();
					this._TimeToTweet = value;
					this.SendPropertyChanged("TimeToTweet");
					this.OnTimeToTweetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetweetingSiteIds", DbType="NVarChar(50)")]
		public string RetweetingSiteIds
		{
			get
			{
				return this._RetweetingSiteIds;
			}
			set
			{
				if ((this._RetweetingSiteIds != value))
				{
					this.OnRetweetingSiteIdsChanging(value);
					this.SendPropertyChanging();
					this._RetweetingSiteIds = value;
					this.SendPropertyChanged("RetweetingSiteIds");
					this.OnRetweetingSiteIdsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecurringTweet")]
	public partial class RecurringTweet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecurringTweetId;
		
		private int _SiteId;
		
		private string _Status;
		
		private System.DateTime _TimeToTweet;
		
		private System.Nullable<int> _PeriodInDays;
		
		private System.Nullable<int> _PeriodInMonths;
		
		private System.Nullable<int> _DayOfMonth;
		
		private System.DateTime _TimeToStopTweeting;
		
		private string _RetweetingSiteIds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecurringTweetIdChanging(int value);
    partial void OnRecurringTweetIdChanged();
    partial void OnSiteIdChanging(int value);
    partial void OnSiteIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTimeToTweetChanging(System.DateTime value);
    partial void OnTimeToTweetChanged();
    partial void OnPeriodInDaysChanging(System.Nullable<int> value);
    partial void OnPeriodInDaysChanged();
    partial void OnPeriodInMonthsChanging(System.Nullable<int> value);
    partial void OnPeriodInMonthsChanged();
    partial void OnDayOfMonthChanging(System.Nullable<int> value);
    partial void OnDayOfMonthChanged();
    partial void OnTimeToStopTweetingChanging(System.DateTime value);
    partial void OnTimeToStopTweetingChanged();
    partial void OnRetweetingSiteIdsChanging(string value);
    partial void OnRetweetingSiteIdsChanged();
    #endregion
		
		public RecurringTweet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringTweetId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecurringTweetId
		{
			get
			{
				return this._RecurringTweetId;
			}
			set
			{
				if ((this._RecurringTweetId != value))
				{
					this.OnRecurringTweetIdChanging(value);
					this.SendPropertyChanging();
					this._RecurringTweetId = value;
					this.SendPropertyChanged("RecurringTweetId");
					this.OnRecurringTweetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="Int NOT NULL")]
		public int SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(140) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeToTweet", DbType="DateTime NOT NULL")]
		public System.DateTime TimeToTweet
		{
			get
			{
				return this._TimeToTweet;
			}
			set
			{
				if ((this._TimeToTweet != value))
				{
					this.OnTimeToTweetChanging(value);
					this.SendPropertyChanging();
					this._TimeToTweet = value;
					this.SendPropertyChanged("TimeToTweet");
					this.OnTimeToTweetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodInDays", DbType="Int")]
		public System.Nullable<int> PeriodInDays
		{
			get
			{
				return this._PeriodInDays;
			}
			set
			{
				if ((this._PeriodInDays != value))
				{
					this.OnPeriodInDaysChanging(value);
					this.SendPropertyChanging();
					this._PeriodInDays = value;
					this.SendPropertyChanged("PeriodInDays");
					this.OnPeriodInDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodInMonths", DbType="Int")]
		public System.Nullable<int> PeriodInMonths
		{
			get
			{
				return this._PeriodInMonths;
			}
			set
			{
				if ((this._PeriodInMonths != value))
				{
					this.OnPeriodInMonthsChanging(value);
					this.SendPropertyChanging();
					this._PeriodInMonths = value;
					this.SendPropertyChanged("PeriodInMonths");
					this.OnPeriodInMonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayOfMonth", DbType="Int")]
		public System.Nullable<int> DayOfMonth
		{
			get
			{
				return this._DayOfMonth;
			}
			set
			{
				if ((this._DayOfMonth != value))
				{
					this.OnDayOfMonthChanging(value);
					this.SendPropertyChanging();
					this._DayOfMonth = value;
					this.SendPropertyChanged("DayOfMonth");
					this.OnDayOfMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeToStopTweeting", DbType="DateTime NOT NULL")]
		public System.DateTime TimeToStopTweeting
		{
			get
			{
				return this._TimeToStopTweeting;
			}
			set
			{
				if ((this._TimeToStopTweeting != value))
				{
					this.OnTimeToStopTweetingChanging(value);
					this.SendPropertyChanging();
					this._TimeToStopTweeting = value;
					this.SendPropertyChanged("TimeToStopTweeting");
					this.OnTimeToStopTweetingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetweetingSiteIds", DbType="NVarChar(50)")]
		public string RetweetingSiteIds
		{
			get
			{
				return this._RetweetingSiteIds;
			}
			set
			{
				if ((this._RetweetingSiteIds != value))
				{
					this.OnRetweetingSiteIdsChanging(value);
					this.SendPropertyChanging();
					this._RetweetingSiteIds = value;
					this.SendPropertyChanged("RetweetingSiteIds");
					this.OnRetweetingSiteIdsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SnabusMailingList")]
	public partial class SnabusMailingListMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Name;
		
		private string _Email;
		
		private string _VerifyCode;
		
		private bool _Verified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnVerifyCodeChanging(string value);
    partial void OnVerifyCodeChanged();
    partial void OnVerifiedChanging(bool value);
    partial void OnVerifiedChanged();
    #endregion
		
		public SnabusMailingListMember()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerifyCode", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VerifyCode
		{
			get
			{
				return this._VerifyCode;
			}
			set
			{
				if ((this._VerifyCode != value))
				{
					this.OnVerifyCodeChanging(value);
					this.SendPropertyChanging();
					this._VerifyCode = value;
					this.SendPropertyChanged("VerifyCode");
					this.OnVerifyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verified", DbType="Bit NOT NULL")]
		public bool Verified
		{
			get
			{
				return this._Verified;
			}
			set
			{
				if ((this._Verified != value))
				{
					this.OnVerifiedChanging(value);
					this.SendPropertyChanging();
					this._Verified = value;
					this.SendPropertyChanged("Verified");
					this.OnVerifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
